# Generated by Django 3.2.6 on 2021-09-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioModel',
            new_name='ImagePortfolio',
        ),
        migrations.CreateModel(
            name='FutureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imglist', models.ImageField(upload_to='images')),
                ('future', models.ManyToManyField(to='articles.FutureModel')),
            ],
        ),
    ]
