# Generated by Django 3.2.6 on 2021-09-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210924_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuremodel',
            name='img',
        ),
    ]
