# Generated by Django 3.2.6 on 2021-09-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_futuremodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futureimage',
            name='future',
        ),
    ]
